language: php

php:
  - 7.2
  - 7.3
  - 7.4

stages:
  - name: analyze
  - name: test

jobs:
  fast_finish: true
  include:
    - stage: analyze
      php: 7.4
      script:
        - composer phpcs
      after_success: skip

before_script:
  - travis_retry composer update --no-interaction --prefer-source  --classmap-authoritative

script:
  - composer tests:coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)