language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "nightly"

matrix:
  allow_failures:
    - php: "nightly"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source  --classmap-authoritative --ignore-platform-reqs

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)