language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "nightly"

matrix:
  allow_failures:
    - php: "nightly"

before_script:
  - travis_retry composer update --no-interaction --prefer-source  --classmap-authoritative --ignore-platform-reqs

script:
  - |
    if [ "$(phpenv version-name)" != 7.1 ]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
